### ISSUE TITLE
Issues Bootcamp feedback

### ISSUE THREAD

**Issue by PaoMlz** [PaoMlz/DEV009-burger-queen-api-client#19]
-Tabajar en Hooks 
-Components de CSS
-Test
-Cors

**Comment by ssinuco** [comment]
Paola te sugiero estos accionables para trabajar despues del bootcamp

- Implementar proyectos de la [curricula](https://github.com/Laboratoria/bootcamp/) para seguir practicando:
- React / React. Te recomiendo Movie Challenge y  Labnotes , aunque tambien podrias implementar cualquiera proyecto de la curricula.
- Fortalecer conceptos de JavaScript y de programacion
- Consultar la documentacion de MDN  https://developer.mozilla.org/en-US/docs/Web/JavaScript
- Consultar https://javascript.info/
- Revisar este repo https://github.com/sudheerj/javascript-interview-questions
- Subir al siguiente nivel con:
- [TailWind](https://tailwindcss.com/)
- [Preprocessors: SCSS vs. LESS vs. Sass](https://medium.com/@rickmint/the-battle-of-the-css-preprocessors-scss-vs-less-vs-sass-a7b667be9c2f)
